### ISSUE TITLE
UACExecutionLevel

### ISSUE THREAD

**Issue by shiek** [notr1ch/TwitchTest#1]
hey Richard,

thanks a lot for TwitchTest.
Why is `<UACExecutionLevel>HighestAvailable</UACExecutionLevel>`?

**Comment by notr1ch** [comment]
The TCP connection stats which TwitchTest uses for the quality metric are only available to applications running as administrator.

https://msdn.microsoft.com/en-us/library/windows/desktop/bb451840(v=vs.85).aspx

**Comment by shiek** [comment]
Alright - thank you!
