### ISSUE TITLE
Failed to parse Twitch Ingest List.

### ISSUE THREAD

**Issue by Kurohitsuki** [notr1ch/TwitchTest#10]
I didn't have this issue with a previous version of this software before. I get this "Failed to Parse Twitch Ingest List." error and cannot use the application.

**Comment by HeshamTB** [comment]
same here. 
Windows 10 1809. 
it worked yesterday.

**Comment by notr1ch** [comment]
This was caused by a Twitch API deprecation, an updated binary was published on r1ch.net. Unfortunately due to moving between PCs a lot my code has become a bit out of sync with this repo, I'll try to clean it up and push the changes.
