### ISSUE TITLE
Servers list bug

### ISSUE THREAD

**Issue by egorovna26** [notr1ch/TwitchTest#11]
![image](https://user-images.githubusercontent.com/23078561/64917809-cc214000-d7be-11e9-910b-24d34747710b.png)

**Comment by notr1ch** [comment]
This is coming from the Twitch API, it's an issue on their end.

**Comment by EgorovnaDev** [comment]
Are you sure about that? I checked loading the list of servers in postman and it works.

**Comment by notr1ch** [comment]
Take a look what https://ingest.twitch.tv/api/v2/ingests returns for you. There is no official API for fetching Twitch ingests, so this endpoint is used by TwitchTest.

**Comment by EgorovnaDev** [comment]
Why api version 2? In the twitch documentation, the current version is v5.
https://dev.twitch.tv/docs/v5/reference/ingests/

**Comment by notr1ch** [comment]
Note that this is an undocumented API endpoint, it is not part of the Kraken API. I specifically chose to use this endpoint over Kraken v5 as "v5 is deprecated and will be shutdown in the future".

**Comment by EgorovnaDev** [comment]
Is it possible then to add a choice of api version?

**Comment by notr1ch** [comment]
Closing as the old API is long gone.
