### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by micsthepick** [notr1ch/TwitchTest#12]
I'm in Australia. The RTT is less than 10 ms, and the bandwidth over 10000, yet the quality is always zero. I'm not partnered or even an affiliate, so I wonder if the twitch servers are discarding packets because 10000 is such a high bandwidth, or if I just have the worlds worst connection? Is there a way to lower the bandwidth that TwitchTest sends so that I can test the connection at a lower bitrate?

**Comment by notr1ch** [comment]
Certain 3rd party network drivers and programs can interfere with the quality metric. If the bandwidth is a consistent 10mbps then I wouldn't worry about it.
