### ISSUE TITLE
Finer-grained server selection

### ISSUE THREAD

**Issue by ghost** [notr1ch/TwitchTest#3]
For instance, I live in the Western US and I know that no matter what I'm never going to get acceptable results off the Eastern US servers. I'd like to be able to checkbox the servers individually so I can pick five or six geo-local servers to test and get my results a bit faster.

Additionally, I'd love an option to save these between sessions so I don't have to re-check things every time I load the tool.

My use case may seem a bit odd, but I'm currently in a major dispute with my ISP that has me running the test tool several times a day right now. This has been going on for two or three months minimum already.

**Comment by MrArca9** [comment]
The server selection support via checkbox is now sitting in pull requests, and should be added soon.
